apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: thanhtantg2003/discovery-server
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_SECURITY_USER_NAME
              value: eureka
            - name: SPRING_SECURITY_USER_PASSWORD
              value: password
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: microservices
spec:
  selector:
    app: discovery-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
