apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-product
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-product
  template:
    metadata:
      labels:
        app: postgres-product
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_DB
              value: product-service
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: tranthanhtan
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-product
  namespace: microservices
spec:
  selector:
    app: postgres-product
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
