apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: thanhtantg2003/inventory-service
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-inventory:5432/inventory-service
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: TranThanhTan.7411
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8761/eureka
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: microservices
spec:
  selector:
    app: inventory-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
